name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/setup-node@master
      with:
          node-version: '10.x'
    - name: prod build
      run: |
        cd FF-Design-Library
        npm install -g @angular/cli        
        npm install
        npm run build --prod --base-href="/Design-Library/"
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: FF-Design-Library/dist
    - name: directory listing task
      run: |
        cd FF-Design-Library
        ls
        cd dist
        ls
